name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  db:
    path: ../db
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

dependency_overrides:
  analyzer: ^5.3.1

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.22.1
